name: Continuous Integration

on:
    pull_request:
    push:
        branches:
        - main
    workflow_dispatch:


permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: mkdir target && chmod 777 target
        - uses: docker://registry.access.redhat.com/ubi8/openjdk-17
          name: package
          with:
            args: >-
                mvn package
        - uses: docker://docker.io/sonarsource/sonar-scanner-cli:4.7
          name: scan-source
          with:
            args: >-
                /opt/sonar-scanner/bin/sonar-scanner -X -Dsonar.projectKey=my-app-trusted-demo
                -Dsonar.sources=./ -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
                -Dsonar.login=${{ secrets.SONARQUEBPROJECTSECRET }} -Dsonar.java.binaries=target/classes