name: Continuous Integration

on:
    pull_request:
    push:
        branches:
        - main
    workflow_dispatch:


permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: docker://docker.io/sonarsource/sonar-scanner-cli:4.7
          with:
            sonarqubeProjectKey: my-quarkus-app
            entrypoint: /bin/sh
            args: >-
                set -x
                env
                pwd
                /opt/sonar-scanner/bin/sonar-scanner -X -Dsonar.projectKey=${{ vars.INPUT_SONARQUBEPROJECTKEY }}
                -Dsonar.sources=./ -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
                -Dsonar.login=${{ secrets.SONARQUEBPROJECTSECRET }} -Dsonar.java.binaries=target/classes