name: Continuous Integration

on:
    pull_request:
    push:
        branches:
        - main
    workflow_dispatch:


permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with: 
            distribution: 'temurin'
            java-version: '17'
        - run: mvn package
        - uses: docker://docker.io/sonarsource/sonar-scanner-cli:4.7
          name: scan-source
          with:
            args: >-
                /opt/sonar-scanner/bin/sonar-scanner -X -Dsonar.projectKey=my-quarkus-app
                -Dsonar.sources=./ -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
                -Dsonar.login=${{ secrets.SONARQUEBPROJECTSECRET }} -Dsonar.java.binaries=target/classes